/* ButtonStatus has been autogenerated by py-apx generator 0.3.4 */

//////////////////////////////////////////////////////////////////////////////
// INCLUDES
//////////////////////////////////////////////////////////////////////////////
#include <string.h>
#include <stdio.h>
#include "ApxNode_ButtonStatus.h"
#include "pack.h"

//////////////////////////////////////////////////////////////////////////////
// CONSTANTS AND DATA TYPES
//////////////////////////////////////////////////////////////////////////////
#define APX_DEFINITON_LEN 352u
#define APX_IN_PORT_DATA_LEN 1u
#define APX_OUT_PORT_DATA_LEN 7u

//////////////////////////////////////////////////////////////////////////////
// LOCAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////
// LOCAL VARIABLES
//////////////////////////////////////////////////////////////////////////////
static const uint8_t m_outPortInitData[APX_OUT_PORT_DATA_LEN]= {
   0, 0, 0, 0, 0, 0, 0
};

static uint8_t m_outPortdata[APX_OUT_PORT_DATA_LEN];
static uint8_t m_outPortDirtyFlags[APX_OUT_PORT_DATA_LEN];
static const uint8_t m_inPortInitData[APX_IN_PORT_DATA_LEN]= {
   15
};

static uint8_t m_inPortdata[APX_IN_PORT_DATA_LEN];
static uint8_t m_inPortDirtyFlags[APX_IN_PORT_DATA_LEN];
static apx_nodeData_t m_nodeData;
static const char *m_apxDefinitionData=
"APX/1.2\n"
"N\"ButtonStatus\"\n"
"T\"PushButtonStatus_T\"C(0,1)\n"
"T\"VehicleMode_T\"C(0,15)\n"
"P\"SWS_PushbuttonStatus_Back\"T[0]:=0\n"
"P\"SWS_PushbuttonStatus_Down\"T[0]:=0\n"
"P\"SWS_PushbuttonStatus_Enter\"T[0]:=0\n"
"P\"SWS_PushbuttonStatus_Home\"T[0]:=0\n"
"P\"SWS_PushbuttonStatus_Left\"T[0]:=0\n"
"P\"SWS_PushbuttonStatus_Right\"T[0]:=0\n"
"P\"SWS_PushbuttonStatus_Up\"T[0]:=0\n"
"R\"VehicleMode\"T[1]:=15\n"
"\n";

//////////////////////////////////////////////////////////////////////////////
// GLOBAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////
apx_nodeData_t * ApxNode_Init_ButtonStatus(void)
{
   memcpy(&m_inPortdata[0], &m_inPortInitData[0], APX_IN_PORT_DATA_LEN);
   memset(&m_inPortDirtyFlags[0], 0, sizeof(m_inPortDirtyFlags));
   memcpy(&m_outPortdata[0], &m_outPortInitData[0], APX_OUT_PORT_DATA_LEN);
   memset(&m_outPortDirtyFlags[0], 0, sizeof(m_outPortDirtyFlags));
   apx_nodeData_create(&m_nodeData, "ButtonStatus", (uint8_t*) &m_apxDefinitionData[0], APX_DEFINITON_LEN, &m_inPortdata[0], &m_inPortDirtyFlags[0], APX_IN_PORT_DATA_LEN, &m_outPortdata[0], &m_outPortDirtyFlags[0], APX_OUT_PORT_DATA_LEN);
   return &m_nodeData;
}

apx_nodeData_t * ApxNode_GetNodeData_ButtonStatus(void)
{
   return &m_nodeData;
}

bool ApxNode_IsConnected_ButtonStatus(void)
{
   return ( apx_nodeData_isInPortDataOpen(&m_nodeData) && apx_nodeData_isOutPortDataOpen(&m_nodeData) );
}

Std_ReturnType ApxNode_Read_ButtonStatus_VehicleMode(VehicleMode_T *val)
{
   *val = (uint8_t) m_inPortdata[0];
   return E_OK;
}

Std_ReturnType ApxNode_Write_ButtonStatus_SWS_PushbuttonStatus_Back(PushButtonStatus_T val)
{
   apx_nodeData_lockOutPortData(&m_nodeData);
   m_outPortdata[0]=(uint8_t) val;
   apx_nodeData_outPortDataWriteNotify(&m_nodeData, 0, 1, false);
   return E_OK;
}

Std_ReturnType ApxNode_Write_ButtonStatus_SWS_PushbuttonStatus_Down(PushButtonStatus_T val)
{
   apx_nodeData_lockOutPortData(&m_nodeData);
   m_outPortdata[1]=(uint8_t) val;
   apx_nodeData_outPortDataWriteNotify(&m_nodeData, 1, 1, false);
   return E_OK;
}

Std_ReturnType ApxNode_Write_ButtonStatus_SWS_PushbuttonStatus_Enter(PushButtonStatus_T val)
{
   apx_nodeData_lockOutPortData(&m_nodeData);
   m_outPortdata[2]=(uint8_t) val;
   apx_nodeData_outPortDataWriteNotify(&m_nodeData, 2, 1, false);
   return E_OK;
}

Std_ReturnType ApxNode_Write_ButtonStatus_SWS_PushbuttonStatus_Home(PushButtonStatus_T val)
{
   apx_nodeData_lockOutPortData(&m_nodeData);
   m_outPortdata[3]=(uint8_t) val;
   apx_nodeData_outPortDataWriteNotify(&m_nodeData, 3, 1, false);
   return E_OK;
}

Std_ReturnType ApxNode_Write_ButtonStatus_SWS_PushbuttonStatus_Left(PushButtonStatus_T val)
{
   apx_nodeData_lockOutPortData(&m_nodeData);
   m_outPortdata[4]=(uint8_t) val;
   apx_nodeData_outPortDataWriteNotify(&m_nodeData, 4, 1, false);
   return E_OK;
}

Std_ReturnType ApxNode_Write_ButtonStatus_SWS_PushbuttonStatus_Right(PushButtonStatus_T val)
{
   apx_nodeData_lockOutPortData(&m_nodeData);
   m_outPortdata[5]=(uint8_t) val;
   apx_nodeData_outPortDataWriteNotify(&m_nodeData, 5, 1, false);
   return E_OK;
}

Std_ReturnType ApxNode_Write_ButtonStatus_SWS_PushbuttonStatus_Up(PushButtonStatus_T val)
{
   apx_nodeData_lockOutPortData(&m_nodeData);
   m_outPortdata[6]=(uint8_t) val;
   apx_nodeData_outPortDataWriteNotify(&m_nodeData, 6, 1, false);
   return E_OK;
}

void ButtonStatus_inPortDataWritten(void *arg, apx_nodeData_t *nodeData, uint32_t offset, uint32_t len)
{
   (void)arg;
   (void)nodeData;
   (void)offset;
   (void)len;
}
//////////////////////////////////////////////////////////////////////////////
// LOCAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////
