name: "unit tests"

# Controls when the action will run. Triggers the workflow on push or pull request
# events for all branches except maintenance_0.2
on:
  push:
    branches-ignore: [ maintenance_0.2 ]
  pull_request:
    branches-ignore: [ maintenance_0.2 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build (${{ matrix.name }})
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: GCC
            os: ubuntu-latest
            cc: gcc
            cxx: g++
          - name: Clang
            os: ubuntu-latest
            cc: clang
            cxx: clang++
          - name: MSVC
            os: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # Build with CMake
    - name: configure (Linux)
      if: runner.os != 'Windows'
      run: cmake -S . -B build -DUNIT_TEST=ON
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}

    - name: configure (Windows)
      if: runner.os == 'Windows'
      run: cmake -S . -B build -DUNIT_TEST=ON

    - name: build
      run: cmake --build build --target apx_unit --config Debug

    # Run unit test suite
    - name: test
      run: ctest --test-dir build -C Debug --output-on-failure
